# Generated by Django 2.0 on 2020-01-12 16:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_auto_20180921_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='CANDIDATO')),
                ('type', models.TextField(choices=[('PRESIDENCIA', 'PRESIDENCIA'), ('CANDIDATO', 'CANDIDATO')], default='CANDIDATO')),
                ('born_area', models.TextField(choices=[('VI', 'Álava'), ('AB', 'Albacete'), ('A', 'Alacant'), ('AL', 'Almería'), ('AV', 'Ávila'), ('BA', 'Badajoz'), ('PM', 'Illes Balears'), ('B', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'Cáceres'), ('CA', 'Cádiz'), ('CS', 'Castelló'), ('CR', 'Ciudad Real'), ('CO', 'Córdoba'), ('C', 'A Coruña'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Gipuzkoa'), ('H', 'Huelva'), ('HU', 'Huesca'), ('J', 'Jaén'), ('LE', 'León'), ('L', 'Lleida'), ('LO', 'La Rioja'), ('LU', 'Lugo'), ('M', 'Madrid'), ('MA', 'Málaga'), ('MU', 'Murcia'), ('NA', 'Nafarroa'), ('OR', 'Ourense'), ('O', 'Asturias'), ('P', 'Palencia'), ('GC', 'Las Palmas'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Sta. Cruz de Tenerife'), ('S', 'Cantabria'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('T', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('V', 'Valéncia'), ('VA', 'Valladolid'), ('BI', 'Bizkaia'), ('ZA', 'Zamora'), ('Z', 'Zaragoza'), ('CE', 'Ceuta'), ('ML', 'Melilla')], default='AB')),
                ('current_area', models.TextField(choices=[('VI', 'Álava'), ('AB', 'Albacete'), ('A', 'Alacant'), ('AL', 'Almería'), ('AV', 'Ávila'), ('BA', 'Badajoz'), ('PM', 'Illes Balears'), ('B', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'Cáceres'), ('CA', 'Cádiz'), ('CS', 'Castelló'), ('CR', 'Ciudad Real'), ('CO', 'Córdoba'), ('C', 'A Coruña'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Gipuzkoa'), ('H', 'Huelva'), ('HU', 'Huesca'), ('J', 'Jaén'), ('LE', 'León'), ('L', 'Lleida'), ('LO', 'La Rioja'), ('LU', 'Lugo'), ('M', 'Madrid'), ('MA', 'Málaga'), ('MU', 'Murcia'), ('NA', 'Nafarroa'), ('OR', 'Ourense'), ('O', 'Asturias'), ('P', 'Palencia'), ('GC', 'Las Palmas'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Sta. Cruz de Tenerife'), ('S', 'Cantabria'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('T', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('V', 'Valéncia'), ('VA', 'Valladolid'), ('BI', 'Bizkaia'), ('ZA', 'Zamora'), ('Z', 'Zaragoza'), ('CE', 'Ceuta'), ('ML', 'Melilla')], default='AB')),
                ('primaries', models.BooleanField(default=False)),
                ('sex', models.TextField(blank=True, choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('start_date_selected', models.DateTimeField(null=True)),
                ('end_date_selected', models.DateTimeField(blank=True, null=True)),
                ('tally', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('postproc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('custom_url', models.CharField(blank=True, max_length=200, null=True)),
                ('auths', models.ManyToManyField(related_name='votings', to='base.Auth')),
                ('candidatures', models.ManyToManyField(related_name='voting', to='voting.CandidatesGroup')),
                ('pub_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting', to='base.Key')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidatesGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.CandidatesGroup'),
        ),
    ]
